"""empty message

Revision ID: 02aab967671c
Revises: 7c4bf46f8dcc
Create Date: 2021-09-02 10:27:30.619298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02aab967671c'
down_revision = '7c4bf46f8dcc'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('current_schedule', sa.String(), nullable=True))
    op.add_column('groups', sa.Column('last_schedule', sa.String(), nullable=True))
    op.drop_column('groups', 'schedule')
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('schedule', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('groups', 'last_schedule')
    op.drop_column('groups', 'current_schedule')
    # ### end Alembic commands ###
