"""empty message

Revision ID: 032e69b07a02
Revises: 13015023f15e
Create Date: 2021-09-01 13:17:01.752506

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '032e69b07a02'
down_revision = '13015023f15e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('timetables', 'last_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timetables', sa.Column('last_date', sa.DATE(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
