"""empty message

Revision ID: 13015023f15e
Revises: 345744862c52
Create Date: 2021-09-01 13:16:17.381208

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '13015023f15e'
down_revision = '345744862c52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('static', 'schedule_date')
    op.add_column('timetables', sa.Column('last_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('timetables', 'last_date')
    op.add_column('static', sa.Column('schedule_date', sa.DATE(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
