"""empty message

Revision ID: 345744862c52
Revises: 68a0b1f6f928
Create Date: 2021-09-01 09:28:18.590766

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '345744862c52'
down_revision = '68a0b1f6f928'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'timetables', 'groups', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'timetables', type_='foreignkey')
    # ### end Alembic commands ###
