"""empty message

Revision ID: 3c6776bfee65
Revises: 05138034f3ec
Create Date: 2021-08-30 13:57:14.805936

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '3c6776bfee65'
down_revision = '05138034f3ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role_code', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('role_name', sa.String(), nullable=False))
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('users', 'role_name')
    op.drop_column('users', 'role_code')
    # ### end Alembic commands ###
