"""empty message

Revision ID: 43449ecb4fcd
Revises: 98c46e3d6f80
Create Date: 2021-08-03 18:00:20.039815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43449ecb4fcd'
down_revision = '98c46e3d6f80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('chat_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'chat_id')
    # ### end Alembic commands ###
