"""empty message

Revision ID: 68a0b1f6f928
Revises: adbe26ecfa6e
Create Date: 2021-09-01 09:24:20.064865

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '68a0b1f6f928'
down_revision = 'adbe26ecfa6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('static',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('comics_date', sa.Date(), nullable=False),
                    sa.Column('schedule_date', sa.Date(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.drop_table('comics')
    op.add_column('timetables', sa.Column('group_id', sa.Integer(), nullable=True))
    op.add_column('timetables', sa.Column('schedule', sa.String(), nullable=True))
    op.drop_column('timetables', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timetables', sa.Column('date', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('timetables', 'schedule')
    op.drop_column('timetables', 'group_id')
    op.create_table('comics',
                    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint('id', 'date', name='comics_pkey')
                    )
    op.drop_table('static')
    # ### end Alembic commands ###
