"""empty message

Revision ID: 7c4bf46f8dcc
Revises: 032e69b07a02
Create Date: 2021-09-01 13:25:44.690720

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '7c4bf46f8dcc'
down_revision = '032e69b07a02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('timetables')
    op.add_column('groups', sa.Column('schedule', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'schedule')
    op.create_table('timetables',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('schedule', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name='timetables_group_id_fkey'),
                    sa.PrimaryKeyConstraint('id', name='timetables_pkey')
                    )
    # ### end Alembic commands ###
