"""empty message

Revision ID: 98c46e3d6f80
Revises: fd424adb8649
Create Date: 2021-08-03 13:21:16.311357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98c46e3d6f80'
down_revision = 'fd424adb8649'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'chat_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('chat_id', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
