"""empty message

Revision ID: adbe26ecfa6e
Revises: 3c6776bfee65
Create Date: 2021-08-31 16:25:07.771648

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'adbe26ecfa6e'
down_revision = '3c6776bfee65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timetables', sa.Column('date', sa.Date(), nullable=True))
    op.drop_constraint('timetables_group_id_fkey', 'timetables', type_='foreignkey')
    op.drop_column('timetables', 'schedule')
    op.drop_column('timetables', 'group_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timetables', sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('timetables',
                  sa.Column('schedule', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.create_foreign_key('timetables_group_id_fkey', 'timetables', 'groups', ['group_id'], ['id'])
    op.drop_column('timetables', 'date')
    # ### end Alembic commands ###
